name: CI
      
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
# Le workflow sera déclenché sur un événement push ou pull sur la branche principale

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
# Système d'exploitation sur lequel s'exécuter
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
    - uses: actions/checkout@v3
# Obtenir le code du référentiel
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Build app
      run: npm run build
    - name: Run tests
      run: npm run test

